# Site settings
title: "Troy David Cook"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "troydavidcook"
resume_title:                   "Web Developer"
resume_contact_email:           "troydavidcook@gmail.com"
resume_contact_telephone:       "(309) 453-6061"
resume_contact_address:         "5025 Broadway Apt 6I New York, NY 10034"
resume_header_contact_info: "5025 Broadway Apt 6I New York, NY 10034 | (309) 453-6061 | troydavidcook@gmail.com"
resume_header_intro: "<p>I’ve always been drawn to design and creation, and I’m very much looking forward to using what I’ve learned over the years to create both engaging and accessable applications, but also apps made with cutting edge tech that looks fantastic, both inside and out.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/troydavidcook"
  resume_twitter_url:           "http://twitter.com/troydavidcook"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/troydavidcook"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://troydavidcook.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
